Add autodetacting so suffix(like .dylib), soflags
Because that, we can also save instuctions
Now we have dylib current version
Also add quotation marks strings in configure
Did more for last commit

diff --git a/configure b/configure
--- a/configure
+++ b/configure
@@ -27,8 +27,9 @@ ar="ar"
 rm="rm"
 build="err"
 cflags='-Wno-variadic-macros -W -Wall -pedantic -c -O2 -I../include'
+soflags=""
 files="`find . -name '*.[ch]'|grep -v hist|grep -v test`"
-
+exesuf=""
 strstr(){  
 	expr match "$1" ".*$2" >/dev/null&&return 0
 	return 1
@@ -61,6 +62,8 @@ for opt do
   --rm=*) rm=`echo $opt | cut -d '=' -f 2`
   ;;
   --extra-cflags=*) cflags="$cflags `echo $opt | cut -d '=' -f 2`"
+  ;;
+  --exesuffix=*) exesuf=`echo $opt | cut -d '=' -f 3`
   ;;
   --help|-h) help_me
   ;;
@@ -99,17 +102,37 @@ echo $cc
 printf "Checking build system type... "
 if [ "$build" = "err" ] ; then 
   case `uname` in
-    Linux|*BSD|Darwin) build=unix
+    Linux|*BSD|Darwin) build="unix"
     ;;
-    MINGW*|MSYS*|CYGWIN*) build=win
+    MINGW*|MSYS*|CYGWIN*) build="win"
     ;;
     *) echo unknown
-      printf '\033[1mconfigure:\033[31mError:\033[30munable to determine system type, please add option --target=win or unix\033[0m\n'
+      printf '\033[1mconfigure:\033[31mError:\033[0munable to determine system type, please add option --target=win or unix\n'
       exit 1
   esac
-  
 fi
 echo $build
+
+printf "Checking suffix for shared objects... "
+if [ "$exesuf" = "" ] ; then
+  case `uname` in
+    Linux|*BSD) exesuf=".so";
+	    soflags="-fPIC -shared -Os"
+    ;;
+    Darwin) exesuf=".dylib"
+	    currentversion="`head include/slib.h -n 31 | tail -n 1 | awk '{print $3}'`.`head include/slib.h -n 33 | tail -n 1 | awk '{print $3}'`.`head include/slib.h -n 34 | tail -n 1 | awk '{print $3}'`"
+	    soflags="-dynamiclib -current_version $currentversion"
+	    ;;
+    MINGW*|MSYS*|CYGWIN*) exesuf=".dll"
+	    soflags="-shared"
+    ;;
+    *) echo unknown
+	    printf '\033[1mconfigure:\033[31mError:\033[0munable to determine suffix for shared objects(aka so/dll), please add option --exesuffix\n'
+      exit 1
+  esac
+fi
+echo $exesuf
+
 echo Generating config.mk
 echo '#config.mk generated by configure'>config.mk
 echo CC=`echo $cc`>>config.mk
@@ -120,6 +143,8 @@ echo CFLAGS-unix=`echo $cflags` -DPLAT=0>>config.mk
 echo BUILD=`echo $build`>>config.mk
 echo PREFIX=`echo $prefix`>>config.mk
 echo FILES=`echo $files`>>config.mk
+echo EXESUF=`echo $exesuf`>>config.mk
+echo SOFLAGS=`echo $soflags`>>config.mk
 
 printf 'configure:\033[32mfinished\033[30m\n'
 
