Add an actual configure

diff --git a/configure b/configure
--- a/configure
+++ b/configure
@@ -1,323 +1,272 @@
 #!/bin/sh
-
-# Autotools-style (./configure) wrapper for CMake
-# <https://github.com/nemequ/configure-cmake>
+# GEN:config.mk
+# 
+#  Guess values for system-dependent variables and create Makefiles.
 #
-#   *** IMPORTANT ***
+#  Copyright (C) 2017, 2018 Zhang Maiyun
 #
-#   You must include the GNUInstallDirs module (which comes with
-#   CMake) in your project.  Just put "include (GNUInstallDirs)" in
-#   you CMakeLists.txt and you should be good.
+# ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
 #
-# This script was originally written for Squash
-# <https://quixdb.github.io/squash/> by Evan Nemerson
-# <evan@nemerson.com>, but has been spun off into a separate
-# repository.  Please feel free to copy it into your own repository,
-# though I would appreciate it if you would post improvements, bugs,
-# feature requests, etc. to the issue tracker at
-# <https://github.com/nemequ/configure-cmake/issues>.
+#  This file is part of the slib.
+#  The slib  is free software; you can redistribute it and/or modify
+#  it under the terms of the GNU Lesser General Public License as published by
+#  the Free Software Foundation; either version 3 of the License, or
+#  (at your option) any later version.
 #
-# To the extent possible under law, the author(s) hereby waive all
-# copyright and related or neighboring rights to this work.  For
-# details, see <https://creativecommons.org/publicdomain/zero/1.0/>
+#  This program is distributed in the hope that it will be useful,
+#  but WITHOUT ANY WARRANTY; without even the implied warranty of
+#  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
+#  GNU Lesser General Public License for more details.
+#
+#  You should have received a copy of the GNU Lesser General Public License
+#  along with this program; if not, write to the Free Software
+#  Foundation, Inc., 59 Temple Place, Suite 330, Boston, MA 02111-1307 USA
+#
+#~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
 
-TOP_SRCDIR="$(dirname $0)"
+# Default/init vaule of variables
+srcdir=`dirname $0`
+cross=""
+prefix="/usr/local"
+libdir=""
+includedir=""
+mandir=""
+infodir=""
+cc="${CC}"
+ar="${AR}"
+rm="rm"
+build=""
+cflags="${CFLAGS} ${CPPFLAGS} -Wno-variadic-macros -W -Wall -pedantic -c -O3 -I${srcdir}/include"
+soflags=""
+cfiles="`cd ${srcdir};find src -type f -name '*.c'`"
+hfiles="`find ${srcdir}/include -type f -name '*.h'`"
+exesuf=""
+# Get constants defined in CMakeLists.txt
+name="libsbl"
+version="`grep project ${srcdir}/CMakeLists.txt|cut -d\  -f3`"
+description="`grep DESCRIPTION ${srcdir}/CMakeLists.txt|cut -f2 -d$'\"'`"
 
-if [ "${CMAKE_CMD}" = "" ]; then
-    CMAKE_CMD="cmake"
-fi
-
-BUILD_TYPE="Debug"
-PREFIX=/usr/local
-LIBDIR=
-CMAKE_ARGS=
-
-if [ -e "${TOP_SRCDIR}/.configure-custom.sh" ]; then
-    . "${TOP_SRCDIR}/.configure-custom.sh"
-fi
-
-if ! command -v cmake > /dev/null;
-then
-    echo "Error: CMake not installed or not in \$PATH!"
-    exit 1
-fi
-
-quote() {
-    echo "$1" | sed -e "s|'|'\\\\''|g; 1s/^/'/; \$s/\$/'/"
+# Function strstr
+strstr(){
+	expr match "$1" ".*$2" >/dev/null&&return 0
+	return 1
 }
 
-extract_var_string() {
-    VAR_NAME=$1
-    VAR_NAME=$(echo $1 | sed -e 's/[ \t]*$//')
-    if [ "x$2" != "x" ]; then
-        VAR_VALUE=$2
+# Header file check
+# $1: name
+check_header(){
+    printf "Checking for $1... "
+    cat > conftest.c << ACEOF
+#include <$1>
+int main(){}
+ACEOF
+    if ! ${cc} conftest.c -o conftest;
+    then
+        echo no
+        rm -f conftest.c conftest conftest.exe
+        return 1
     else
-        VAR_VALUE=yes
-    fi
-
-    if [ "x$3" != "x" ]; then
-        VAR_UC_NAME=$3
-    else
-        VAR_UC_NAME=$(echo "$1" | tr '[:lower:]' '[:upper:]' | tr -c '[:alnum:]' '_' | sed 's/_$//g')
-    fi
-}
-
-set_config_var() {
-    is_with=n
-    case "$1" in
-        "--enable-"*)
-            name="${1#--enable-}"
-            cfg="${ENABLE_VARS}"
-            ;;
-        "--disable-"*)
-            name="${1#--disable-}";
-            cfg="${DISABLE_VARS}";
-            ;;
-        "--with-"*)
-            # IFS="=" read -ra WITHARGS <<< "${1}"
-            name="${1#--with-}"
-            cfg="${WITH_VARS}"
-            is_with=y
-            ;;
-    esac
-
-    found=n
-    for varstring in $cfg; do
-        extract_var_string $(echo "${varstring}" | tr '|' ' ')
-        if [ "x$VAR_NAME" = "x$name" ]; then
-            found=y
-            break;
-        fi
-    done
-
-    if [ "$found" = "y" ]; then
-        if [ "x$is_with" = "xy" ]; then
-            CMAKE_ARGS="$CMAKE_ARGS -D${VAR_UC_NAME}=$(quote "$2")"
-        else
-            CMAKE_ARGS="$CMAKE_ARGS -D${VAR_UC_NAME}=$(quote "${VAR_VALUE}")"
-        fi
-    else
-        echo "Unknown parameter: ${1}"
-        exit 1
+        echo yes
+        rm -f conftest.c conftest conftest.exe
+        return 0
     fi
 }
 
-prefix_to_offset() {
-    expr $(echo "${1}" | awk '{ print length }') + 1
+# Help
+help_me()
+{
+	printf 'Usage: %s/configure [option=<vaule> | --help]\n' ${srcdir}
+	printf 'Options:\n'
+	printf '  --prefix=PREFIX\tSet prefix;\n'
+	printf '  --build=BUILD\tconfigure for building on BUILD [guessed]'
+	printf '  --host=HOST\tcross-compile to build programs to run on HOST [BUILD]'
+	printf '  --target=TARGET\tIgnored'
+    printf '  --rm=RM\tSet remover(Should support "-f" option);\n'
+	printf '  --exesuf=SUFFIX\tSet suffix of shared objects;\n'
+	printf '  --soflags=SOFLAGS\tSet CFLAGS for shared objects\n'
+	printf '  --{bin,lib,include,man,info}dir=DIR\t Set bindir, libdir, includedir, mandir, infodir;\n'
+	printf '  --help,-h\tDisplay this help information.\n\n'
+    printf 'Some influential environment variables:'
+    printf '  AR\tlibmaker'
+    printf '  CC\tC compiler'
+    printf '  CFLAGS\tC flags'
+	printf '\nProject maintained by Zhang Maiyun <myzhang1029@163.com>.\n'
+	exit 0
 }
 
-print_help() {
-    cat <<EOF >&2
-  -h, --help              display this help and exit
-  --disable-debug         disable debugging mode
-  --pass-thru             pass remaining arguments through to CMake
-
-  --prefix=PREFIX         install architecture-independent files in PREFIX
-                          [$PREFIX]
-  --bindir=DIR            user executables [PREFIX/bin]
-  --sbindir=DIR           system admin executables [PREFIX/sbin]
-  --libexecdir=DIR        program executables [PREFIX/libexec]
-  --sysconfdir=DIR        read-only single-machine data [PREFIX/etc]
-  --sharedstatedir=DIR    modifiable architecture-independent data [PREFIX/com]
-  --localstatedir=DIR     modifiable single-machine data [PREFIX/var]
-  --libdir=DIR            object code libraries [PREFIX/lib]
-  --includedir=DIR        C header files [PREFIX/include]
-  --oldincludedir=DIR     C header files for non-gcc [/usr/include]
-  --datarootdir=DIR       read-only arch.-independent data root [PREFIX/share]
-  --datadir=DIR           read-only architecture-independent data [DATAROOTDIR]
-  --infodir=DIR           info documentation [DATAROOTDIR/info]
-  --localedir=DIR         locale-dependent data [DATAROOTDIR/locale]
-  --mandir=DIR            man documentation [DATAROOTDIR/man]
-  --docdir=DIR            documentation root [DATAROOTDIR/doc/PROJECT_NAME]
-EOF
-
-    first=y
-    for varstring in ${ENABLE_VARS}; do
-        if [ $first = 'y' ]; then
-            echo ""
-            first=n
-        fi
-        extract_var_string $(echo "${varstring}" | tr '|' ' ')
-        var_doc_name="ENABLE_${VAR_UC_NAME}_DOC"
-        eval "docstring=\$$var_doc_name"
-        if [ "x${docstring}" = "x" ]; then
-            printf "  --enable-%-14s enable %s support\n" "${VAR_NAME}" "$(echo -n "${VAR_NAME}" | tr '-' ' ')"
-        else
-            printf "  --enable-%-14s %s\n" "${VAR_NAME}" "$docstring"
-        fi
-    done
-
-    first=y
-    for varstring in ${DISABLE_VARS}; do
-        if [ $first = 'y' ]; then
-            echo ""
-            first=n
-        fi
-        extract_var_string $(echo "${varstring}" | tr '|' ' ')
-        var_doc_name="DISABLE_${VAR_UC_NAME}_DOC"
-        eval "docstring=\$$var_doc_name"
-        if [ "x${docstring}" = "x" ]; then
-            printf "  --disable-%-13s disable %s support\n" "${VAR_NAME}" "$(echo -n "${VAR_NAME}" | tr '-' ' ')"
-        else
-            printf "  --disable-%-13s %s\n" "${VAR_NAME}" "$docstring"
-        fi
-    done
-
-    first=y
-    for varstring in ${WITH_VARS}; do
-        if [ $first = 'y' ]; then
-            echo ""
-            first=n
-        fi
-        extract_var_string $(echo "${varstring}" | tr '|' ' ')
-        var_doc_name="WITH_${VAR_UC_NAME}_DOC"
-        eval "docstring=\$$var_doc_name"
-        paraminfo="${VAR_NAME}=${VAR_VALUE}"
-        if [ "x${docstring}" = "x" ]; then
-            printf "  --with-%-16s enable %s support\n" "$paraminfo" "$(echo -n "${VAR_NAME}" | tr '-' ' ')"
-        else
-            printf "  --with-%-16s %s\n" "$paraminfo" "$docstring"
-        fi
-    done
-
-    exit 0
-}
-
-while [ $# != 0 ]; do
-    case "$1" in
-        "--prefix="*)
-            PREFIX="${1#*=}";;
-        "--prefix")
-            PREFIX="${2}"; shift;;
-        "--bindir="*)
-            CMAKE_ARGS="$CMAKE_ARGS -DCMAKE_INSTALL_BINDIR=$(quote "${1#*=}")";;
-        "--bindir")
-            CMAKE_ARGS="$CMAKE_ARGS -DCMAKE_INSTALL_BINDIR=$(quote "$2")"; shift;;
-        "--sbindir="*)
-            CMAKE_ARGS="$CMAKE_ARGS -DCMAKE_INSTALL_SBINDIR=$(quote "${1#*=}")";;
-        "--sbindir")
-            CMAKE_ARGS="$CMAKE_ARGS -DCMAKE_INSTALL_SBINDIR=$(quote "$2")"; shift;;
-        "--libexecdir="*)
-            CMAKE_ARGS="$CMAKE_ARGS -DCMAKE_INSTALL_LIBEXECDIR=$(quote "${1#*=}")";;
-        "--libexecdir")
-            CMAKE_ARGS="$CMAKE_ARGS -DCMAKE_INSTALL_LIBEXECDIR=$(quote "$2")"; shift;;
-        "--sysconfdir="*)
-            CMAKE_ARGS="$CMAKE_ARGS -DCMAKE_INSTALL_SYSCONFDIR=$(quote "${1#*=}")";;
-        "--sysconfdir")
-            CMAKE_ARGS="$CMAKE_ARGS -DCMAKE_INSTALL_SYSCONFDIR=$(quote "$2")"; shift;;
-        "--sharedstatedir="*)
-            CMAKE_ARGS="$CMAKE_ARGS -DCMAKE_INSTALL_SHAREDSTATEDIR=$(quote "${1#*=}")";;
-        "--sharedstatedir")
-            CMAKE_ARGS="$CMAKE_ARGS -DCMAKE_INSTALL_SHAREDSTATEDIR=$(quote "$2")"; shift;;
-        "--localstatedir="*)
-            CMAKE_ARGS="$CMAKE_ARGS -DCMAKE_INSTALL_LOCALSTATEDIR=$(quote "${1#*=}")";;
-        "--localstatedir")
-            CMAKE_ARGS="$CMAKE_ARGS -DCMAKE_INSTALL_LOCALSTATEDIR=$(quote "$2")"; shift;;
-        "--libdir="*)
-            LIBDIR="${1#*=}";;
-        "--libdir")
-            LIBDIR="${2}"; shift;;
-        "--includedir="*)
-            CMAKE_ARGS="$CMAKE_ARGS -DCMAKE_INSTALL_INCLUDEDIR=$(quote "${1#*=}")";;
-        "--includedir")
-            CMAKE_ARGS="$CMAKE_ARGS -DCMAKE_INSTALL_INCLUDEDIR=$(quote "$2")"; shift;;
-        "--oldincludedir="*)
-            CMAKE_ARGS="$CMAKE_ARGS -DCMAKE_INSTALL_OLDINCLUDEDIR=$(quote "${1#*=}")";;
-        "--oldincludedir")
-            CMAKE_ARGS="$CMAKE_ARGS -DCMAKE_INSTALL_OLDINCLUDEDIR=$(quote "$2")"; shift;;
-        "--datarootdir="*)
-            CMAKE_ARGS="$CMAKE_ARGS -DCMAKE_INSTALL_DATAROOTDIR=$(quote "${1#*=}")";;
-        "--datarootdir")
-            CMAKE_ARGS="$CMAKE_ARGS -DCMAKE_INSTALL_DATAROOTDIR=$(quote "$2")"; shift;;
-        "--datadir="*)
-            CMAKE_ARGS="$CMAKE_ARGS -DCMAKE_INSTALL_DATADIR=$(quote "${1#*=}")";;
-        "--datadir")
-            CMAKE_ARGS="$CMAKE_ARGS -DCMAKE_INSTALL_DATADIR=$(quote "$2")"; shift;;
-        "--infodir="*)
-            CMAKE_ARGS="$CMAKE_ARGS -DCMAKE_INSTALL_INFODIR=$(quote "${1#*=}")";;
-        "--infodir")
-            CMAKE_ARGS="$CMAKE_ARGS -DCMAKE_INSTALL_INFODIR=$(quote "$2")"; shift;;
-        "--localedir="*)
-            CMAKE_ARGS="$CMAKE_ARGS -DCMAKE_INSTALL_LOCALEDIR=$(quote "${1#*=}")";;
-        "--localedir")
-            CMAKE_ARGS="$CMAKE_ARGS -DCMAKE_INSTALL_LOCALEDIR=$(quote "$2")"; shift;;
-        "--mandir="*)
-            CMAKE_ARGS="$CMAKE_ARGS -DCMAKE_INSTALL_MANDIR=$(quote "${1#*=}")";;
-        "--mandir")
-            CMAKE_ARGS="$CMAKE_ARGS -DCMAKE_INSTALL_MANDIR=$(quote "$2")"; shift;;
-        "--docdir="*)
-            CMAKE_ARGS="$CMAKE_ARGS -DCMAKE_INSTALL_DOCDIR=$(quote "${1#*=}")";;
-        "--docdir")
-            CMAKE_ARGS="$CMAKE_ARGS -DCMAKE_INSTALL_DOCDIR=$(quote "$2")"; shift;;
-
-        "CC="*)
-            CMAKE_ARGS="$CMAKE_ARGS -DCMAKE_C_COMPILER=$(quote "${1#*=}")";;
-        "CXX="*)
-            CMAKE_ARGS="$CMAKE_ARGS -DCMAKE_CXX_COMPILER=$(quote "${1#*=}")";;
-        "CFLAGS="*)
-            CMAKE_ARGS="$CMAKE_ARGS -DCMAKE_C_FLAGS=$(quote "${1#*=}")";;
-        "CXXFLAGS="*)
-            CMAKE_ARGS="$CMAKE_ARGS -DCMAKE_CXX_FLAGS=$(quote "${1#*=}")";;
-        "LDFLAGS="*)
-            LDFLAGS="$LDFLAGS ${1#*=}";;
-
-        "--help")
-            print_help;;
-        "-h")
-            print_help;;
-
-        # This flag is the only one which may be a bit surprising to
-        # people.  Autotools always builds with debugging symbols enabled
-        # (AFAIK), but for cmake you have to do -DCMAKE_BUILD_TYPE=Debug.
-        # Unfortunately this can change other things as well, so although
-        # I realize there is no --disable-debug flag I thought it would be
-        # prudent to support one here.
-        "--disable-debug")
-            BUILD_TYPE="Release";;
-
-        "--pass-thru")
-            while [ $# != 1 ]; do
-                shift;
-                CMAKE_ARGS="$CMAKE_ARGS $(quote "${1}")";
-            done;;
-
-        "--enable-"*)
-            set_config_var "$1"
-            ;;
-
-        "--disable-"*)
-            set_config_var "$1"
-            ;;
-
-        "--with-"*)
-            name=$(echo "${1#--with-}" | awk '{split($1,v,"="); print v[1]}')
-            case "${1}" in
-                "--with-${name}="*)
-                    set_config_var "--with-${name}" "${1#--with-${name}=}";;
-                "--with-${name}")
-                    set_config_var "$1" "$2";
-                    shift;;
-            esac
-            ;;
-
-        *)
-            echo "$0: error: unrecognized option: \`$1'" >&2
-            echo "Try \`$0 --help' for more information" >&2
-            exit -1
-    esac;
-    shift
+# Parse arguments
+for opt do
+  eval opt=\"${opt}\"
+  case "${opt}" in
+  --prefix=*) prefix=`echo ${opt} | cut -d '=' -f 2`
+  ;;
+  --host=*) cross=`echo ${opt} | cut -d '=' -f 2`
+  ;;
+  --build=*)
+  ;;
+  --target=*)
+  ;;
+  --rm=*) rm=`echo ${opt} | cut -d '=' -f 2`
+  ;;
+  --exesuffix=*) exesuf=`echo ${opt} | cut -d '=' -f 2`
+  ;;
+  --bindir=*) bindir=`echo ${opt} | cut -d '=' -f 2`
+  ;;
+  --libdir=*) libdir=`echo ${opt} | cut -d '=' -f 2`
+  ;;
+  --includedir=*) includedir=`echo ${opt} | cut -d '=' -f 2`
+  ;;
+  --mandir=*) mandir=`echo ${opt} | cut -d '=' -f 2`
+  ;;
+  --infodir=*) infodir=`echo ${opt} | cut -d '=' -f 2`
+  ;;
+  --soflags=*) soflags="${soflags} `echo ${opt} | cut -d '=' -f 2`"
+  ;;
+  --help|-h) help_me
+  ;;
+  *) printf '\033[1mconfigure: \033[33mWarning: \033[0munrecognized option %s\n' "${opt}"
+  ;;
+  esac
 done
 
-if [ "x${LIBDIR}" = "x" ]; then
-    LIBDIR="${PREFIX}/lib"
+w=0
+# Check for C compiler
+printf "Checking for C Compiler... "
+if [ "$cc" = "" ] ; then
+  if ${cross}-clang -v > /dev/null 2>&1; then
+    cc="${cross}-clang"
+  elif ${cross}-gcc -v > /dev/null 2>&1; then
+    cc="${cross}-gcc"
+    cflags="-Wno-misleading-indentation $cflags"
+  elif ${cross}-tcc -v > /dev/null 2>&1; then
+    cc="${cross}-tcc"
+  elif ${cross}-cc -v > /dev/null 2>&1; then
+    cc="${cross}-cc"
+  elif clang -v > /dev/null 2>&1; then
+    cc="clang"
+    w=1
+  elif gcc -v > /dev/null 2>&1; then
+    cc="gcc"
+    w=1
+    cflags="-Wno-misleading-indentation $cflags"
+  elif tcc -v > /dev/null 2>&1; then
+    cc="tcc"
+    w=1
+  elif cc -v > /dev/null 2>&1; then
+    cc="cc"
+    w=1
+  else
+    echo no
+    printf '\033[1mconfigure: \033[31mError: \033[30mNo C compiler found!\nPlease specify. Read "./configure --help" for more infomation\033[0m\n'
+    exit 1
+  fi
+else 
+  strstr "$cc" "gcc" && cflags="-Wno-misleading-indentation $cflags"
+fi
+echo $cc
+if [ "$cross" != "" ] && [ $w -eq 1 ];
+then
+    echo '\033[1mconfigure: \033[33mWarning: \033[0musing unprefixed cc when cross-compiling'
 fi
 
-# Unlike CFLAGS/CXXFLAGS/CC/CXX, LDFLAGS isn't handled by CMake, so we
-# need to parse it here.
-if [ "x${LDFLAGS}" != "x" ]; then
-    for varname in EXE MODULE SHARED STATIC; do
-        CMAKE_ARGS="$CMAKE_ARGS -DCMAKE_${varname}_LINKER_FLAGS=$(quote "$LDFLAGS")"
-    done
+w=0
+# Check for ar
+printf "Checking for ar... "
+if [ "$ar" = "" ] ; then
+  if which ${cross}-ar > /dev/null 2>&1; then
+    ar="${cross}-ar"
+  elif which ar > /dev/null 2>&1; then
+    ar="ar"
+    w=1
+  else
+    echo no
+    printf '\033[1mconfigure: \033[31mError: \033[30mNo ar found!\nPlease specify. Read "./configure --help" for more infomation\033[0m\n'
+    exit 1
+  fi
+fi
+echo $ar
+if [ "$cross" != "" ] && [ $w -eq 1 ];
+then
+    echo '\033[1mconfigure: \033[33mWarning: \033[0musing unprefixed ar when cross-compiling'
 fi
 
-eval "${CMAKE_CMD}" "${TOP_SRCDIR}" -DCMAKE_BUILD_TYPE="${BUILD_TYPE}" -DCMAKE_INSTALL_PREFIX="${PREFIX}" -DCMAKE_INSTALL_LIBDIR="${LIBDIR}" ${CMAKE_ARGS}
+# For exesuf
+printf "Checking suffix for shared objects... "
+
+if [ "$exesuf" = "" ] ; then
+  case `uname` in
+    Linux|*BSD|GNU) exesuf=".so";
+	    soflags="-fPIC -shared -Os"
+    ;;
+    Darwin) exesuf=".dylib";
+	    soflags="-dynamiclib -current_version $version"
+    ;;
+    MINGW*|MSYS*|CYGWIN*) exesuf=".dll";soflags="-shared"
+    ;;
+    *) echo unknown
+	    printf '\033[1mconfigure: \033[31mError: \033[0munable to determine suffix for shared objects(aka dylib/so/dll), please add option --exesuffix\n'
+      exit 1
+  esac
+fi
+echo $exesuf
+
+if check_header "alloca.h";
+then
+    alloca_h=1
+else
+    alloca_h=0
+fi
+
+if check_header "fcntl.h";
+then
+    fcntl_h=1
+else
+    fcntl_h=0
+fi
+
+if check_header "termios.h";
+then
+    termios_h=1
+else
+    termios_h=0
+fi
+
+if check_header "unistd.h";
+then
+    unistd_h=1
+else
+    unistd_h=0
+fi
+
+if [ "$libdir" = "" ] ; then
+	libdir="$prefix/lib"
+fi
+if [ "$includedir" = "" ] ; then
+	includedir="$prefix/include"
+fi
+
+# Write output
+echo Generating config.mk
+echo '# config.mk generated by configure'>config.mk
+echo CC=`echo $cc`>>config.mk
+echo AR=`echo $ar`>>config.mk
+echo RM=`echo $rm`>>config.mk
+echo CFLAGS=`echo $cflags`>>config.mk
+echo PREFIX=`echo $prefix`>>config.mk
+echo SRCDIR=`echo $srcdir`>>config.mk
+echo CFILES=`echo $cfiles`>>config.mk
+echo HFILES=`echo $hfiles`>>config.mk
+echo EXESUF=`echo $exesuf`>>config.mk
+echo SOFLAGS=`echo $soflags`>>config.mk
+echo LIBDIR=`echo $libdir`>>config.mk
+echo INCLUDEDIR=`echo $includedir`>>config.mk
+cp ${srcdir}/Makefile.in Makefile
+
+echo Generating sbl.pc
+sed "s,@CMAKE_INSTALL_PREFIX@,${prefix},;s,@CMAKE_INSTALL_LIBDIR@,lib,;\
+    s,@CMAKE_INSTALL_INCLUDEDIR@,include,;s,@PROJECT_NAME@,${name},;\
+    s,@PROJECT_DESCRIPTION@,${description},;\
+    s,@PROJECT_VERSION@,${version},;" ${srcdir}/sbl.pc.in > sbl.pc
+
+echo Generating config.h
+printf 'configure: \033[32mfinished\033[30m\n'
