Add compiler check

diff --git a/configure b/configure
--- a/configure
+++ b/configure
@@ -4,7 +4,7 @@
 # Licence:LGPL
 
 prefix='/usr/local'
-cc="gcc"
+cc=""
 ar="ar"
 rm="rm"
 build="err"
@@ -55,16 +55,37 @@ for opt do
   esac
 done
 
+if [ "$cc" = "" ] ; then
+  printf "Checking for C Compiler.. "
+  if clang -v > /dev/null 2>&1; then
+    cc="clang"
+    echo clang
+  elif gcc -v > /dev/null 2>&1; then
+    cc="gcc"
+    echo gcc
+  elif tcc -v > /dev/null 2>&1; then
+    cc="tcc"
+    echo tcc
+  elif cc -v > /dev/null 2>&1; then
+    cc="cc"
+    echo cc
+  else
+    echo no
+    printf '\033[1mconfigure:\033[31mError:\033[30mNo C compiler found!\n\tPlease specify. Read "./configure --help" for more infomation\033[0m\n'
+    exit 1
+  fi
+fi
+    
 if [ "$build" = "err" ] ; then 
   printf "Checking build system type.. "
   case `uname` in
-  Linux|*BSD|Darwin) build=unix
-  ;;
-  MINGW*|MSYS*|CYGWIN*) build=win
-  ;;
-  *) echo unknown
-     printf '\033[1mconfigure:\033[31mError:\033[30munable to determine system type, please add option --target=win or unix\033[0m\n'
-     exit 1
+    Linux|*BSD|Darwin) build=unix
+    ;;
+    MINGW*|MSYS*|CYGWIN*) build=win
+    ;;
+    *) echo unknown
+      printf '\033[1mconfigure:\033[31mError:\033[30munable to determine system type, please add option --target=win or unix\033[0m\n'
+      exit 1
   esac
   echo $build
 fi
