Some bug-fix in making stage
 * Remove macro FILE
 * Add error on wrong system type
 * Write prefix in config.mk
 * Finish commit 8055c1e

diff --git a/configure b/configure
--- a/configure
+++ b/configure
@@ -11,16 +11,7 @@ target="err"
 cflags='-Os -shared -fPIC'
 cflags_win='-O2 -DPLAT=1 -pedantic -W -Wall -Wno-variadic-macros -c -I../include -lm'
 cflags_unix='-O2 -DPLAT=0 -pedantic -W -Wall -Wno-variadic-macros -c -I../include -lm'
-files='file/fcopy.c file/fsize.c file/iofile.c \
-      main/colorprintf.c main/error.c main/getch.c \
-      main/itoa.c main/mysh.c main/randomnum.c\
-      main/sbl.c main/mret.c main/getopt.c\
-      math/average.c math/calc.c math/eular.c math/gcf.c math/ispn.c\
-      math/isrp.c math/lcm.c math/prtpn.c \
-      stack/clearstack.c stack/destorystack.c stack/getlen.c \
-      stack/initstack.c stack/pop.c stack/push.c \
-      string/module.c string/mtscat.c \
-      include/slib.h'
+
 help_me()
 {
 	echo 'Usage: configure [option][=vaule]'
@@ -64,8 +55,8 @@ echo ' #
  #
  #~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
 
-CFLAGS-WIN=-O2 -DPLAT=1 -pedantic -W -Wall -Wno-variadic-macros -c  -I../include -lm 
-CFLAGS-UNIX=-O2 -DPLAT=0 -pedantic -W -Wall -Wno-variadic-macros -c -I../include -lm
+CFLAGS-WIN=-O2 -DPLAT=1 -W -Wall -Wno-variadic-macros -c  -I../include -lm 
+CFLAGS-UNIX=-O2 -DPLAT=0 -W -Wall -Wno-variadic-macros -c -I../include -lm
 CFLAGS=-Os -shared -fPIC
 
 PREFIX=/usr/local
@@ -74,19 +65,13 @@ TARGET=err
 CC=gcc
 RM=rm
 AR=ar
-
-FILES=file/fcopy.c file/fsize.c file/iofile.c \
-      main/colorprintf.c main/error.c main/getch.c \
-      main/itoa.c main/mysh.c main/randomnum.c\
-      main/sbl.c main/mret.c main/getopt.c\
-      math/average.c math/calc.c math/eular.c math/gcf.c math/ispn.c\
-      math/isrp.c math/lcm.c math/prtpn.c \
-      stack/clearstack.c stack/destorystack.c stack/getlen.c \
-      stack/initstack.c stack/pop.c stack/push.c \
-      string/module.c string/mtscat.c \
-      include/slib.h
 ' > config.mk
-rm config.mk~
+echo configure:Rewrited config.mk
+
+if [ -f config.mk~ ] ;then
+  rm config.mk~
+  echo configure:Removed config.mk~
+fi
 exit 0
 }
 
@@ -101,11 +86,16 @@ for opt do
   ;;
   --rm=*) rm=`echo $opt | cut -d '=' -f 2`
   ;;
-  --extra-cflags=*) cflags_win="$cflags_win `echo $opt | cut -d '=' -f 2`"; cflags_unix="$cflags_unix `echo $opt | cut -d '=' -f 2`"
+  --extra-cflags=*) cflags_win="$cflags_win `echo $opt | cut -d '=' -f 2`"
+  cflags_unix="$cflags_unix `echo $opt | cut -d '=' -f 2`"
   ;;
   --help|-h) help_me
   ;;
-  --target=*) target=`echo $opt |cut -d '=' -f 2`
+  --target=*) target=`echo $opt | cut -d '=' -f 2`
+  if [ "$target" != "unix" ] && [ "$target" != "win" ] ; then
+    echo configure:unknown system type \"$target\", type \"./configure --help\" for more infomation
+    exit 1
+  fi
   ;;
   --revert) revert
   ;;
@@ -115,13 +105,17 @@ for opt do
 done
 
 if [ "$target" = "err" ] ; then 
+  printf "Checking build system type "
   case `uname` in
   Linux|*BSD|Darwin) target=unix
   ;;
   MINGW*|MSYS*|CYGWIN*) target=win
   ;;
-  *) echo 'configure: Error:unable to determine system type, please add option --target=win or unix';exit 1
+  *) echo unknown
+     echo 'configure: Error:unable to determine system type, please add option --target=win or unix'
+     exit 1
   esac
+  echo $target
 fi
 
 if [ -f config.mk ] ; then
@@ -137,5 +131,6 @@ echo CFLAGS=`echo $cflags`>>config.mk
 echo CFLAGS-WIN=`echo $cflags_win`>>config.mk
 echo CFLAGS-UNIX=`echo $cflags_unix`>>config.mk
 echo TARGET=`echo $target`>>config.mk
+echo PREFIX=`echo $prefix`>>config.mk
 echo configure:Generated config.mk
 
